### ISSUE TITLE
How do you install the app to your team?

### ISSUE THREAD

**Issue by david-drinn** [slackapi/Slack-Python-Onboarding-Tutorial#3]
The [final step](https://github.com/slackapi/Slack-Python-Onboarding-Tutorial/blob/master/docs/Section-5.md) doesn't delve into the details of _how_ to install the app to your team.

This could mean it's either so easy that it doesn't warrant covering that step in this tutorial, or it could mean it's too complicated and out of scope for this tutorial. 

Either way, I've been spinning my wheels. Any help?

**Comment by david-drinn** [comment]
You can install your customer app in the [Slack Button section](https://api.slack.com/docs/slack-button#). Go down to "Add the Slack Button" section, and check all the boxes for good measure -- "incoming webhook", "commands", and "bot" -- and then click the button "Add to Slack". Follow the prompts here to install it to your team, and select a channel.

It seems you can go through this to add to other channels, or it you can invite the bot to a channel.

**Comment by david-drinn** [comment]
@karishay Are you available to add a step for this part?

**Comment by karishay** [comment]
Meep! Perhaps I should make that more clear. 

Once your server is running in the terminal, open a browser window and navigate to `localhost:5000/install` and you should see a very bare looking webpage like this:

<img width="915" alt="screen shot 2017-01-17 at 4 47 48 pm" src="https://cloud.githubusercontent.com/assets/4828352/22046336/c35c13ba-dcd4-11e6-95ee-31b8dee57a18.png">

Then click on the button and you'll be directed to a page that asks you which team you'd like to install the app onto. Here's what mine looks like: 

<img width="655" alt="screen shot 2017-01-17 at 4 48 39 pm" src="https://cloud.githubusercontent.com/assets/4828352/22046365/f71b6700-dcd4-11e6-942a-cc4ae36fdd44.png">

Then you'll get to a page which shows you what permissions the app will need in order to work, which you'll need to approve.

<img width="530" alt="screen shot 2017-01-17 at 4 50 00 pm" src="https://cloud.githubusercontent.com/assets/4828352/22046396/32fd0b48-dcd5-11e6-9478-b5436eae6185.png">

And then you should get a very bare bones thank you page: 

<img width="485" alt="screen shot 2017-01-17 at 4 52 40 pm" src="https://cloud.githubusercontent.com/assets/4828352/22046427/630619d8-dcd5-11e6-8d17-d6a0c4d8ba8b.png">

**Comment by karishay** [comment]
Hey @david-drinn let me know if this was what you were looking for. 

There's a few common gotchas that in getting the server running properly if you're not seeing the install or thank you pages load. If you're running into that, here's a few things that might help:
* Is your virtualenv turned on where you're running `python app.py`?
* Are your environment variables exported correctly? 
(`echo $CLIENT_ID $CLIENT_SECRET $VERIFICATION_TOKEN`)
* Restart ngrok and update the redirect url (in you Slack app's **OAuth & Permissions** page) and the request url (in your Slack app's **Events Subscription** page) with the new ngrok https address

I'll close this issue for now but feel free to open a new one or send me an email if you're having more issues. 😸

**Comment by david-drinn** [comment]
That's great, thanks! 

In fact it's too nice to be buried here. Could it be added to the step-by-step guide?

**Comment by ostriandoni** [comment]
I still can't install bot on another workspace. Let's say I create bot app on workspace-A and will distribute it to another workspace-B even though after following steps has been done:
localhost:5000/install -> add to slack -> select team -> authorize -> landing page thank you appear -> check on workspace-B, there is no bot there.
